apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    domain: app
spec:
  replicas: 5
  selector:
    matchLabels:
      domain: app
  template:
    metadata:
      name: app-template
      labels:
        domain: app
    spec:
      containers:
        - name: app-image
          image: {{.Values.image}}
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: appsecrets
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: name
                  name: appsecrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: appsecrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: appsecrets
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 8000